# this file is part of the autofirma-docker project
#
# Copyright (C) 2025  Gonzalo Ruiz <rgon (at) outlook (dot) com>
# Copyright (C) 2025  Joaquín Cuéllar Padilla <joa (dot) cuellar (at) riseup (dot) net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '3'
services:
  firefox:
    build: .
    ports:
      - "5800:3000"
    volumes:
      - "/docker/appdata/firefox:/config:rw"
      - "./certificates:/config/certificates:ro"
      - "./config:/config/.config/openbox/:rw"
      - "./documents:/config/documents:rw"
    environment:
      FIREFOX_CLI: https://www.sededgsfp.gob.es/es/Paginas/TestAutofirma.aspx
      _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp
