version: '3'
services:
  firefox:
    build: .
    ports:
      - "5800:3000"
    volumes:
      - "/docker/appdata/firefox:/config:rw"
      - "./certificates:/config/certificates:ro"
    environment:
      FIREFOX_CLI: https://sede.carm.es/cryptoApplet/ayuda/probarautofirma.html
      _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp